# This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

# To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

# It's also a requirement to have Docker and the docker-compose plugin installed in your environment

# To launch this app without having to clone the entire repository, use the docker-compose.yaml file to run the app

version: "3.8"

services:

  # Builds the frontend Docker image and creates the frontend microservice
  yolo-client:
    image: petermwenda/yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - yolo-network

  # Builds the backend Docker image and creates the backend microservice
  yolo-backend:
    image: petermwenda/yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - yolo-mongo
    networks:
      - yolo-network

  # Creates the database microservice
  yolo
