version: "3.8"

services:
  # Builds the frontend Docker image and creates the frontend microservice
  yolo-client:
    image: petermwenda/yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - yolo-network

  # Builds the backend Docker image and creates the backend microservice
  yolo-backend:
    image: petermwenda/yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - yolo-mongo
    networks:
      - yolo-network

  # Creates the database microservice (MongoDB)
  yolo-mongo:
    image: mongo:latest
    container_name: yolo-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - yolo-network
    volumes:
      - yolo-mongo-data:/data/db  # Persist data to a volume

networks:
  yolo-network:
    driver: bridge

volumes:
  yolo-mongo-data:
    driver: local

