---
- name: Pull frontend Docker image
  docker_image:
    name: petermwenda/yolo-client:v1.0.0
    source: pull

- name: Run frontend container
  docker_container:
    name: yolo-client
    image: petermwenda/yolo-client:v1.0.0
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    networks:
      - name: app-net
  tags:
    - frontend
