---
- name: Pull MongoDB Docker image
  docker_image:
    name: mongo
    source: pull

- name: Run MongoDB container
  docker_container:
    name: yolo-mongo
    image: mongo
    state: started
    restart_policy: always
    ports:
      - "27017:27017"
    volumes:
      - ./app-mongo-data:/data/db
    networks:
      - name: app-net
  tags:
    - database

