---
- name: Pull backend image
  docker_image:
    name: petermwenda/yolo-backend:v1.0.0
    source: pull

- name: Run backend container
  docker_container:
    name: yolo-backend
    image: petermwenda/yolo-backend:v1.0.0
    state: started
    ports:
      - "5000:5000"
    networks:
      - name: app-net
    env:
      MONGO_URL: mongodb://yolo-mongo:27017/yolo

